version: "3.8"

services:
  envoy_new:
    build: ./envoy
    ports:
      - "9095:9095"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "500M"  # 500 MB
        reservations:
          cpus: "1.0"
          memory: "500M"

  backend_new:
    build: ./backend
    ports:
      - "8083:8083"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"  # 1 GB
        reservations:
          cpus: "2.0"
          memory: "1G"
  
  auth:
    build: ./Auth
    ports:
      - "9002:9002"
    networks:
      - proxy_network

  
  backend2_new:
    build: ./backend2
    ports:
      - "8082:8082"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1G"  # 1 GB

  varnish_new:
    build: ./varnish
    ports:
      - "8080:80"
    networks:
      - proxy_network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500M"  # 500 MB
        reservations:
          cpus: "0.5"
          memory: "500M"
    environment:
      ORG1_CACHE_MAX_SIZE: "3221225472"  # 3GB
      ORG2_CACHE_MAX_SIZE: "1073741824"  # 1GB
      DEFAULT_CACHE_MAX_SIZE: "1048576"   # 1MB
    command: 
       -s default=malloc,1G
       -s org1=malloc,3G
       -s org2=malloc,1G

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - proxy_network

  ratelimit:
    image: envoyproxy/ratelimit:master
    command: /bin/ratelimit
    ports:
      - 9090:9090
      - 8081:8081
      - 6070:6070
    depends_on:
      - redis
    networks:
      - proxy_network
    # change the paths
    volumes:
      - ./ratelimit:/data/ratelimit/config
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit
      - RUNTIME_WATCH_ROOT=false
      - CONFIG_TYPE=${CONFIG_TYPE:-FILE}
      - CONFIG_GRPC_XDS_NODE_ID=test-node-id
      - CONFIG_GRPC_XDS_SERVER_URL=ratelimit-xds-config-server:18000

networks:
  proxy_network:
    driver: bridge
